(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val check_users_saved_albums : ids:string -> bool list Lwt.t
val get_an_album : id:string -> ?market:string -> unit -> Album_object.t Lwt.t
val get_an_albums_tracks : id:string -> ?market:string -> ?limit:int32 -> ?offset:int32 -> unit -> Simplified_tracks_paging_object.t Lwt.t
val get_an_artists_albums : id:string -> ?include_groups:string -> ?market:string -> ?limit:int32 -> ?offset:int32 -> unit -> Albums_paging_object.t Lwt.t
val get_multiple_albums : ids:string -> ?market:string -> unit -> Get_multiple_albums_200_response.t Lwt.t
val get_new_releases : ?country:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_new_releases_200_response.t Lwt.t
val get_users_saved_albums : ?limit:int32 -> ?offset:int32 -> ?market:string -> unit -> Get_users_saved_albums_200_response.t Lwt.t
val remove_albums_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val save_albums_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
