(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

let check_users_saved_albums ~ids =
    let open Lwt.Infix in
    let uri = Request.build_uri "/me/albums/contains" in
    let headers = Request.default_headers in
    let uri = Request.add_query_param uri "ids" (fun x -> x) ids in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as_list_of (JsonSupport.to_bool) resp body

let get_an_album ~id ?market () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/albums/{id}" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.maybe_add_query_param uri "market" (fun x -> x) market in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Album_object.of_yojson) resp body

let get_an_albums_tracks ~id ?market ?(limit = 20l) ?(offset = 0l) () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/albums/{id}/tracks" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.maybe_add_query_param uri "market" (fun x -> x) market in
    let uri = Request.add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.add_query_param uri "offset" Int32.to_string offset in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Simplified_tracks_paging_object.of_yojson) resp body

let get_an_artists_albums ~id ?include_groups ?market ?(limit = 20l) ?(offset = 0l) () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/artists/{id}/albums" in
    let headers = Request.default_headers in
    let uri = Request.replace_path_param uri "id" (fun x -> x) id in
    let uri = Request.maybe_add_query_param uri "include_groups" (fun x -> x) include_groups in
    let uri = Request.maybe_add_query_param uri "market" (fun x -> x) market in
    let uri = Request.add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.add_query_param uri "offset" Int32.to_string offset in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Albums_paging_object.of_yojson) resp body

let get_multiple_albums ~ids ?market () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/albums" in
    let headers = Request.default_headers in
    let uri = Request.add_query_param uri "ids" (fun x -> x) ids in
    let uri = Request.maybe_add_query_param uri "market" (fun x -> x) market in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Get_multiple_albums_200_response.of_yojson) resp body

let get_new_releases ?country ?(limit = 20l) ?(offset = 0l) () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/browse/new-releases" in
    let headers = Request.default_headers in
    let uri = Request.maybe_add_query_param uri "country" (fun x -> x) country in
    let uri = Request.add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.add_query_param uri "offset" Int32.to_string offset in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Get_new_releases_200_response.of_yojson) resp body

let get_users_saved_albums ?(limit = 20l) ?(offset = 0l) ?market () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/me/albums" in
    let headers = Request.default_headers in
    let uri = Request.add_query_param uri "limit" Int32.to_string limit in
    let uri = Request.add_query_param uri "offset" Int32.to_string offset in
    let uri = Request.maybe_add_query_param uri "market" (fun x -> x) market in
    Cohttp_lwt_unix.Client.call `GET uri ~headers >>= fun (resp, body) ->
    Request.read_json_body_as (JsonSupport.unwrap Get_users_saved_albums_200_response.of_yojson) resp body

let remove_albums_user ~ids ~request_body () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/me/albums" in
    let headers = Request.default_headers in
    let uri = Request.add_query_param uri "ids" (fun x -> x) ids in
    let body = Request.write_as_json_body (JsonSupport.of_map_of ) request_body in
    Cohttp_lwt_unix.Client.call `DELETE uri ~headers ~body >>= fun (resp, body) ->
    Request.handle_unit_response resp

let save_albums_user ~ids ~request_body () =
    let open Lwt.Infix in
    let uri = Request.build_uri "/me/albums" in
    let headers = Request.default_headers in
    let uri = Request.add_query_param uri "ids" (fun x -> x) ids in
    let body = Request.write_as_json_body (JsonSupport.of_map_of ) request_body in
    Cohttp_lwt_unix.Client.call `PUT uri ~headers ~body >>= fun (resp, body) ->
    Request.handle_unit_response resp

