(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_a_categories_playlists : category_id:string -> ?country:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_a_categories_playlists_200_response.t Lwt.t
val get_a_category : category_id:string -> ?country:string -> ?locale:string -> unit -> Category_object.t Lwt.t
val get_categories : ?country:string -> ?locale:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_categories_200_response.t Lwt.t
