(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_recommendation_genres : unit -> Get_recommendation_genres_200_response.t Lwt.t
