(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val change_playlist_details : playlist_id:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val check_current_user_follows : _type:Enums.type_0 -> ids:string -> bool list Lwt.t
val check_users_saved_albums : ids:string -> bool list Lwt.t
val check_users_saved_episodes : ids:string -> bool list Lwt.t
val check_users_saved_shows : ids:string -> bool list Lwt.t
val check_users_saved_tracks : ids:string -> bool list Lwt.t
val create_playlist : user_id:string -> request_body:(string * String.t) list -> unit -> Playlist_object.t Lwt.t
val follow_artists_users : _type:Enums.type_0 -> ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val get_a_list_of_current_users_playlists : ?limit:int32 -> ?offset:int32 -> unit -> Playlists_paging_object.t Lwt.t
val get_followed : _type:Enums.artistobject_type -> ?after:string -> ?limit:int32 -> unit -> Get_followed_200_response.t Lwt.t
val get_users_saved_albums : ?limit:int32 -> ?offset:int32 -> ?market:string -> unit -> Get_users_saved_albums_200_response.t Lwt.t
val get_users_saved_episodes : ?market:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_users_saved_episodes_200_response.t Lwt.t
val get_users_saved_shows : ?limit:int32 -> ?offset:int32 -> unit -> Get_users_saved_shows_200_response.t Lwt.t
val get_users_saved_tracks : ?market:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_users_saved_tracks_200_response.t Lwt.t
val get_users_top_artists : ?time_range:string -> ?limit:int32 -> ?offset:int32 -> unit -> Artists_paging_object.t Lwt.t
val get_users_top_tracks : ?time_range:string -> ?limit:int32 -> ?offset:int32 -> unit -> Tracks_paging_object.t Lwt.t
val remove_albums_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val remove_episodes_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val remove_shows_user : ids:string -> ?market:string -> save_shows_user_request_t:Save_shows_user_request.t -> unit -> unit Lwt.t
val remove_tracks_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val save_albums_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val save_episodes_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val save_shows_user : ids:string -> save_shows_user_request_t:Save_shows_user_request.t -> unit -> unit Lwt.t
val save_tracks_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val unfollow_artists_users : _type:Enums.type_0 -> ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
