(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val get_available_markets : unit -> Get_available_markets_200_response.t Lwt.t
