(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val add_tracks_to_playlist : playlist_id:string -> ?position:int32 -> ?uris:string -> request_body:(string * String.t) list -> unit -> Reorder_or_replace_playlists_tracks_200_response.t Lwt.t
val change_playlist_details : playlist_id:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val check_if_user_follows_playlist : playlist_id:string -> ids:string -> bool list Lwt.t
val create_playlist : user_id:string -> request_body:(string * String.t) list -> unit -> Playlist_object.t Lwt.t
val follow_playlist : playlist_id:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val get_a_categories_playlists : category_id:string -> ?country:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_a_categories_playlists_200_response.t Lwt.t
val get_a_list_of_current_users_playlists : ?limit:int32 -> ?offset:int32 -> unit -> Playlists_paging_object.t Lwt.t
val get_featured_playlists : ?country:string -> ?locale:string -> ?timestamp:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_featured_playlists_200_response.t Lwt.t
val get_list_users_playlists : user_id:string -> ?limit:int32 -> ?offset:int32 -> unit -> Playlists_paging_object.t Lwt.t
val get_playlist : playlist_id:string -> ?market:string -> ?fields:string -> ?additional_types:string -> unit -> Playlist_object.t Lwt.t
val get_playlist_cover : playlist_id:string -> Image_object.t list Lwt.t
val get_playlists_tracks : playlist_id:string -> ?market:string -> ?fields:string -> ?limit:int32 -> ?offset:int32 -> ?additional_types:string -> unit -> Playlist_tracks_paging_object.t Lwt.t
val remove_tracks_playlist : playlist_id:string -> remove_tracks_playlist_request_t:Remove_tracks_playlist_request.t -> unit -> Reorder_or_replace_playlists_tracks_200_response.t Lwt.t
val reorder_or_replace_playlists_tracks : playlist_id:string -> ?uris:string -> request_body:(string * String.t) list -> unit -> Reorder_or_replace_playlists_tracks_200_response.t Lwt.t
val unfollow_playlist : playlist_id:string -> unit Lwt.t
val upload_custom_playlist_cover : playlist_id:string -> body:string -> unit Lwt.t
