(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val add_to_queue : uri:string -> ?device_id:string -> unit -> unit Lwt.t
val get_a_users_available_devices : unit -> Devices_object.t Lwt.t
val get_information_about_the_users_current_playback : ?market:string -> ?additional_types:string -> unit -> Currently_playing_context_object.t Lwt.t
val get_recently_played : ?limit:int32 -> ?after:int32 -> ?before:int32 -> unit -> Get_recently_played_200_response.t Lwt.t
val get_the_users_currently_playing_track : ?market:string -> ?additional_types:string -> unit -> Currently_playing_object.t Lwt.t
val pause_a_users_playback : ?device_id:string -> unit -> unit Lwt.t
val seek_to_position_in_currently_playing_track : position_ms:int32 -> ?device_id:string -> unit -> unit Lwt.t
val set_repeat_mode_on_users_playback : state:string -> ?device_id:string -> unit -> unit Lwt.t
val set_volume_for_users_playback : volume_percent:int32 -> ?device_id:string -> unit -> unit Lwt.t
val skip_users_playback_to_next_track : ?device_id:string -> unit -> unit Lwt.t
val skip_users_playback_to_previous_track : ?device_id:string -> unit -> unit Lwt.t
val start_a_users_playback : ?device_id:string -> request_body:(string * Any_type.t) list -> unit -> unit Lwt.t
val toggle_shuffle_for_users_playback : state:bool -> ?device_id:string -> unit -> unit Lwt.t
val transfer_a_users_playback : request_body:(string * Any_type.t) list -> unit -> unit Lwt.t
