(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val search : q:string -> _type:Enums.type_1 list -> ?market:string -> ?limit:int32 -> ?offset:int32 -> ?include_external:Enums.include_external -> unit -> Search_200_response.t Lwt.t
