(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

val add_tracks_to_playlist : playlist_id:string -> ?position:int32 -> ?uris:string -> request_body:(string * String.t) list -> unit -> Reorder_or_replace_playlists_tracks_200_response.t Lwt.t
val check_users_saved_tracks : ids:string -> bool list Lwt.t
val get_an_albums_tracks : id:string -> ?market:string -> ?limit:int32 -> ?offset:int32 -> unit -> Simplified_tracks_paging_object.t Lwt.t
val get_an_artists_top_tracks : id:string -> ?market:string -> unit -> Get_an_artists_top_tracks_200_response.t Lwt.t
val get_audio_analysis : id:string -> Audio_analysis_object.t Lwt.t
val get_audio_features : id:string -> Audio_features_object.t Lwt.t
val get_playlists_tracks : playlist_id:string -> ?market:string -> ?fields:string -> ?limit:int32 -> ?offset:int32 -> ?additional_types:string -> unit -> Playlist_tracks_paging_object.t Lwt.t
val get_recommendations : seed_artists:string -> seed_genres:string -> seed_tracks:string -> ?limit:int32 -> ?market:string -> ?min_acousticness:float -> ?max_acousticness:float -> ?target_acousticness:float -> ?min_danceability:float -> ?max_danceability:float -> ?target_danceability:float -> ?min_duration_ms:int32 -> ?max_duration_ms:int32 -> ?target_duration_ms:int32 -> ?min_energy:float -> ?max_energy:float -> ?target_energy:float -> ?min_instrumentalness:float -> ?max_instrumentalness:float -> ?target_instrumentalness:float -> ?min_key:int32 -> ?max_key:int32 -> ?target_key:int32 -> ?min_liveness:float -> ?max_liveness:float -> ?target_liveness:float -> ?min_loudness:float -> ?max_loudness:float -> ?target_loudness:float -> ?min_mode:int32 -> ?max_mode:int32 -> ?target_mode:int32 -> ?min_popularity:int32 -> ?max_popularity:int32 -> ?target_popularity:int32 -> ?min_speechiness:float -> ?max_speechiness:float -> ?target_speechiness:float -> ?min_tempo:float -> ?max_tempo:float -> ?target_tempo:float -> ?min_time_signature:int32 -> ?max_time_signature:int32 -> ?target_time_signature:int32 -> ?min_valence:float -> ?max_valence:float -> ?target_valence:float -> unit -> Recommendations_object.t Lwt.t
val get_several_audio_features : ids:string -> Get_several_audio_features_200_response.t Lwt.t
val get_several_tracks : ids:string -> ?market:string -> unit -> Get_an_artists_top_tracks_200_response.t Lwt.t
val get_track : id:string -> ?market:string -> unit -> Track_object.t Lwt.t
val get_users_saved_tracks : ?market:string -> ?limit:int32 -> ?offset:int32 -> unit -> Get_users_saved_tracks_200_response.t Lwt.t
val get_users_top_tracks : ?time_range:string -> ?limit:int32 -> ?offset:int32 -> unit -> Tracks_paging_object.t Lwt.t
val remove_tracks_playlist : playlist_id:string -> remove_tracks_playlist_request_t:Remove_tracks_playlist_request.t -> unit -> Reorder_or_replace_playlists_tracks_200_response.t Lwt.t
val remove_tracks_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
val reorder_or_replace_playlists_tracks : playlist_id:string -> ?uris:string -> request_body:(string * String.t) list -> unit -> Reorder_or_replace_playlists_tracks_200_response.t Lwt.t
val save_tracks_user : ids:string -> request_body:(string * String.t) list -> unit -> unit Lwt.t
