(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The artists of the album. Each artist object includes a link in `href` to more detailed information about the artist.  *)
    artists: Simplified_artist_object.t list;
    (* The tracks of the album.  *)
    tracks: Simplified_tracks_paging_object.t option [@default None];
    (* The popularity of the album, with 100 being the most popular. The popularity is calculated from the popularity of the album's individual tracks. *)
    popularity: int32 option [@default None];
    (* The label for the album. *)
    label: string option [@default None];
    (* Known external IDs for the album.  *)
    external_ids: External_id_object.t option [@default None];
    (* A list of the genres used to classify the album. (If not yet classified, the array is empty.) *)
    genres: string list;
    (* The copyright statements of the album. *)
    copyrights: Copyright_object.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    artists = [];
    tracks = None;
    popularity = None;
    label = None;
    external_ids = None;
    genres = [];
    copyrights = [];
}

