(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The cursor to use as key to find the next page of items. *)
    after: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    after = None;
}

