(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* [International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code)  *)
    isrc: string option [@default None];
    (* [International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29)  *)
    ean: string option [@default None];
    (* [Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code)  *)
    upc: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    isrc = None;
    ean = None;
    upc = None;
}

