(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    audio_features: Audio_features_object.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (audio_features : Audio_features_object.t list) : t = {
    audio_features = audio_features;
}

