(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    uris: string list;
    (* The position of the first item to be reordered.  *)
    range_start: int32 option [@default None];
    (* The position where the items should be inserted.<br>To reorder the items to the end of the playlist, simply set _insert_before_ to the position after the last item.<br>Examples:<br>To reorder the first item to the last position in a playlist with 10 items, set _range_start_ to 0, and _insert_before_ to 10.<br>To reorder the last item in a playlist with 10 items to the start of the playlist, set _range_start_ to 9, and _insert_before_ to 0.  *)
    insert_before: int32 option [@default None];
    (* The amount of items to be reordered. Defaults to 1 if not set.<br>The range of items to be reordered begins from the _range_start_ position, and includes the _range_length_ subsequent items.<br>Example:<br>To move the items at index 9-10 to the start of the playlist, _range_start_ is set to 9, and _range_length_ is set to 2.  *)
    range_length: int32 option [@default None];
    (* The playlist's snapshot ID against which you want to make the changes.  *)
    snapshot_id: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    uris = [];
    range_start = None;
    insert_before = None;
    range_length = None;
    snapshot_id = None;
}

