(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The exact number of audio samples analyzed from this track. See also `analysis_sample_rate`. *)
  num_samples : int32 option; [@default None]
  (* Length of the track in seconds. *)
  duration : float option; [@default None]
  (* This field will always contain the empty string. *)
  sample_md5 : string option; [@default None]
  (* An offset to the start of the region of the track that was analyzed. (As the entire track is analyzed, this should always be 0.) *)
  offset_seconds : int32 option; [@default None]
  (* The length of the region of the track was analyzed, if a subset of the track was analyzed. (As the entire track is analyzed, this should always be 0.) *)
  window_seconds : int32 option; [@default None]
  (* The sample rate used to decode and analyze this track. May differ from the actual sample rate of this track available on Spotify. *)
  analysis_sample_rate : int32 option; [@default None]
  (* The number of channels used for analysis. If 1, all channels are summed together to mono before analysis. *)
  analysis_channels : int32 option; [@default None]
  (* The time, in seconds, at which the track's fade-in period ends. If the track has no fade-in, this will be 0.0. *)
  end_of_fade_in : float option; [@default None]
  (* The time, in seconds, at which the track's fade-out period starts. If the track has no fade-out, this should match the track's length. *)
  start_of_fade_out : float option; [@default None]
  (* The overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typically range between -60 and 0 db.  *)
  loudness : float option; [@default None]
  (* The overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration.  *)
  tempo : float option; [@default None]
  (* The confidence, from 0.0 to 1.0, of the reliability of the `tempo`. *)
  tempo_confidence : float option; [@default None]
  (* An estimated time signature. The time signature (meter) is a notational convention to specify how many beats are in each bar (or measure). The time signature ranges from 3 to 7 indicating time signatures of \''3/4\'', to \''7/4\''. *)
  time_signature : int32 option; [@default None]
  (* The confidence, from 0.0 to 1.0, of the reliability of the `time_signature`. *)
  time_signature_confidence : float option; [@default None]
  (* The key the track is in. Integers map to pitches using standard [Pitch Class notation](https://en.wikipedia.org/wiki/Pitch_class). E.g. 0 = C, 1 = C♯/D♭, 2 = D, and so on. If no key was detected, the value is -1.  *)
  key : int32 option; [@default None]
  (* The confidence, from 0.0 to 1.0, of the reliability of the `key`. *)
  key_confidence : float option; [@default None]
  (* Mode indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0.  *)
  mode : int32 option; [@default None]
  (* The confidence, from 0.0 to 1.0, of the reliability of the `mode`. *)
  mode_confidence : float option; [@default None]
  (* An [Echo Nest Musical Fingerprint (ENMFP)](https://academiccommons.columbia.edu/doi/10.7916/D8Q248M4) codestring for this track. *)
  codestring : string option; [@default None]
  (* A version number for the Echo Nest Musical Fingerprint format used in the codestring field. *)
  code_version : float option; [@default None]
  (* An [EchoPrint](https://github.com/spotify/echoprint-codegen) codestring for this track. *)
  echoprintstring : string option; [@default None]
  (* A version number for the EchoPrint format used in the echoprintstring field. *)
  echoprint_version : float option; [@default None]
  (* A [Synchstring](https://github.com/echonest/synchdata) for this track. *)
  synchstring : string option; [@default None]
  (* A version number for the Synchstring used in the synchstring field. *)
  synch_version : float option; [@default None]
  (* A Rhythmstring for this track. The format of this string is similar to the Synchstring. *)
  rhythmstring : string option; [@default None]
  (* A version number for the Rhythmstring used in the rhythmstring field. *)
  rhythm_version : float option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    num_samples = None;
    duration = None;
    sample_md5 = None;
    offset_seconds = None;
    window_seconds = None;
    analysis_sample_rate = None;
    analysis_channels = None;
    end_of_fade_in = None;
    start_of_fade_out = None;
    loudness = None;
    tempo = None;
    tempo_confidence = None;
    time_signature = None;
    time_signature_confidence = None;
    key = None;
    key_confidence = None;
    mode = None;
    mode_confidence = None;
    codestring = None;
    code_version = None;
    echoprintstring = None;
    echoprint_version = None;
    synchstring = None;
    synch_version = None;
    rhythmstring = None;
    rhythm_version = None;
  }
