(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* A list of 0..n Device objects *)
    devices: Device_object.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    devices = [];
}

