(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The show on which the episode belongs.  *)
  show : Simplified_show_object.t;
}
[@@deriving yojson { strict = false }, show]

let create (show : Simplified_show_object.t) : t = { show }
