(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Episode_base_restrictions.t : Included in the response when a content restriction is applied. See [Restriction Object](/documentation/web-api/reference/#object-episoderestrictionobject) for more details. 
 *)

type t = {
    (* The reason for the restriction. Supported values:<br> - `market` - The content item is not available in the given market.<br> - `product` - The content item is not available for the user's subscription type.<br> - `explicit` - The content item is explicit and the user's account is set to not play explicit content.<br> Additional reasons may be added in the future. **Note**: If you use this field, make sure that your application safely handles unknown values.  *)
    reason: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Included in the response when a content restriction is applied. See [Restriction Object](/documentation/web-api/reference/#object-episoderestrictionobject) for more details.  *)
let create () : t = {
    reason = None;
}

