(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The HTTP status code (also returned in the response header; see [Response Status Codes](/documentation/web-api/#response-status-codes) for more information).  *)
  status : int32;
  (* A short description of the cause of the error.  *)
  message : string;
}
[@@deriving yojson { strict = false }, show]

let create (status : int32) (message : string) : t = { status; message }
