(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { genres : string list } [@@deriving yojson { strict = false }, show]

let create (genres : string list) : t = { genres }
