(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* A description of the playlists *)
  message : string;
  playlists : Playlists_paging_object.t;
}
[@@deriving yojson { strict = false }, show]

let create (message : string) (playlists : Playlists_paging_object.t) : t =
  { message; playlists }
