(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = { categories : Get_categories_200_response_categories.t }
[@@deriving yojson { strict = false }, show]

let create (categories : Get_categories_200_response_categories.t) : t =
  { categories }
