(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The source URL of the image.  *)
    url: string;
    (* The image height in pixels.  *)
    height: int32 option;
    (* The image width in pixels.  *)
    width: int32 option;
} [@@deriving yojson { strict = false }, show ];;

let create (url : string) (height : int32 option) (width : int32 option) : t = {
    url = url;
    height = height;
    width = width;
}

