(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The name displayed on the user's profile. `null` if not available.  *)
  display_name : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t = { display_name = None }
