(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Playlist_track_object_added_by.t : The Spotify user who added the track or episode. _**Note**: some very old playlists may return `null` in this field._ 
 *)

type t = {
    external_urls: Public_user_object_external_urls.t option [@default None];
    followers: Public_user_object_followers.t option [@default None];
    (* A link to the Web API endpoint for this user.  *)
    href: string option [@default None];
    (* The [Spotify user ID](/documentation/web-api/#spotify-uris-and-ids) for this user.  *)
    id: string option [@default None];
    (* The object type.  *)
    _type: Enums.publicuserobject_type option [@default Some(`User)];
    (* The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for this user.  *)
    uri: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The Spotify user who added the track or episode. _**Note**: some very old playlists may return `null` in this field._  *)
let create () : t = {
    external_urls = None;
    followers = None;
    href = None;
    id = None;
    _type = None;
    uri = None;
}

