(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The number of tracks available after min\\_\\* and max\\_\\* filters have been applied.  *)
  after_filtering_size : int32 option; [@default None]
  (* The number of tracks available after relinking for regional availability.  *)
  after_relinking_size : int32 option; [@default None]
  (* A link to the full track or artist data for this seed. For tracks this will be a link to a [Track Object](/documentation/web-api/reference/#object-trackobject). For artists a link to [an Artist Object](/documentation/web-api/reference/#object-artistobject). For genre seeds, this value will be `null`.  *)
  href : string option; [@default None]
  (* The id used to select this seed. This will be the same as the string used in the `seed_artists`, `seed_tracks` or `seed_genres` parameter.  *)
  id : string option; [@default None]
  (* The number of recommended tracks available for this seed.  *)
  initial_pool_size : int32 option; [@default None]
  (* The entity type of this seed. One of `artist`, `track` or `genre`.  *)
  _type : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    after_filtering_size = None;
    after_relinking_size = None;
    href = None;
    id = None;
    initial_pool_size = None;
    _type = None;
  }
