(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  external_urls : Artist_object_external_urls.t option; [@default None]
  (* A link to the Web API endpoint providing full details of the artist.  *)
  href : string option; [@default None]
  (* The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the artist.  *)
  id : string option; [@default None]
  (* The name of the artist.  *)
  name : string option; [@default None]
  (* The object type.  *)
  _type : Enums.artistobject_type option; [@default Some `Artist]
  (* The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the artist.  *)
  uri : string option; [@default None]
}
[@@deriving yojson { strict = false }, show]

let create () : t =
  {
    external_urls = None;
    href = None;
    id = None;
    name = None;
    _type = None;
    uri = None;
  }
