(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* The field is present when getting an artist's albums. Compare to album_type this field represents relationship between the artist and the album.  *)
  album_group : Enums.album_group option; [@default None]
  (* The artists of the album. Each artist object includes a link in `href` to more detailed information about the artist.  *)
  artists : Simplified_artist_object.t list;
}
[@@deriving yojson { strict = false }, show]

let create (artists : Simplified_artist_object.t list) : t =
  { album_group = None; artists }
