(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Album_base_restrictions.t : Included in the response when a content restriction is applied. 
 *)

type t = {
    (* The reason for the restriction. Albums may be restricted if the content is not available in a given market, to the user's subscription type, or when the user's account is set to not play explicit content. Additional reasons may be added in the future.  *)
    reason: Enums.reason option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** Included in the response when a content restriction is applied.  *)
let create () : t = {
    reason = None;
}

