(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    external_urls: Artist_object_external_urls.t option [@default None];
    followers: Artist_object_followers.t option [@default None];
    (* A list of the genres the artist is associated with. If not yet classified, the array is empty.  *)
    genres: string list;
    (* A link to the Web API endpoint providing full details of the artist.  *)
    href: string option [@default None];
    (* The [Spotify ID](/documentation/web-api/#spotify-uris-and-ids) for the artist.  *)
    id: string option [@default None];
    (* Images of the artist in various sizes, widest first.  *)
    images: Image_object.t list;
    (* The name of the artist.  *)
    name: string option [@default None];
    (* The popularity of the artist. The value will be between 0 and 100, with 100 being the most popular. The artist's popularity is calculated from the popularity of all the artist's tracks.  *)
    popularity: int32 option [@default None];
    (* The object type.  *)
    _type: Enums.artistobject_type option [@default Some(`Artist)];
    (* The [Spotify URI](/documentation/web-api/#spotify-uris-and-ids) for the artist.  *)
    uri: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    external_urls = None;
    followers = None;
    genres = [];
    href = None;
    id = None;
    images = [];
    name = None;
    popularity = None;
    _type = None;
    uri = None;
}

