(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    meta: Audio_analysis_object_meta.t option [@default None];
    track: Audio_analysis_object_track.t option [@default None];
    (* The time intervals of the bars throughout the track. A bar (or measure) is a segment of time defined as a given number of beats. *)
    bars: Time_interval_object.t list;
    (* The time intervals of beats throughout the track. A beat is the basic time unit of a piece of music; for example, each tick of a metronome. Beats are typically multiples of tatums. *)
    beats: Time_interval_object.t list;
    (* Sections are defined by large variations in rhythm or timbre, e.g. chorus, verse, bridge, guitar solo, etc. Each section contains its own descriptions of tempo, key, mode, time_signature, and loudness. *)
    sections: Section_object.t list;
    (* Each segment contains a roughly conisistent sound throughout its duration. *)
    segments: Segment_object.t list;
    (* A tatum represents the lowest regular pulse train that a listener intuitively infers from the timing of perceived musical events (segments). *)
    tatums: Time_interval_object.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    meta = None;
    track = None;
    bars = [];
    beats = [];
    sections = [];
    segments = [];
    tatums = [];
}

