(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Cursor_paging_object_cursors.t : The cursors used to find the next set of items.
 *)

type t = {
    (* The cursor to use as key to find the next page of items. *)
    after: string option [@default None];
} [@@deriving yojson { strict = false }, show ];;

(** The cursors used to find the next set of items. *)
let create () : t = {
    after = None;
}

