(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    albums: Albums_paging_object.t;
} [@@deriving yojson { strict = false }, show ];;

let create (albums : Albums_paging_object.t) : t = {
    albums = albums;
}

