(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The episodes of the show.  *)
    episodes: Episodes_paging_object.t;
} [@@deriving yojson { strict = false }, show ];;

let create (episodes : Episodes_paging_object.t) : t = {
    episodes = episodes;
}

