(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The starting point (in seconds) of the time interval. *)
    start: float option [@default None];
    (* The duration (in seconds) of the time interval. *)
    duration: float option [@default None];
    (* The confidence, from 0.0 to 1.0, of the reliability of the interval. *)
    confidence: float option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    start = None;
    duration = None;
    confidence = None;
}

