(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* A JSON array containing the ID of the device on which playback should be started/transferred.<br>For example:`{device_ids:[\''74ASZWbe4lXaubB36ztrGX\'']}`<br>_**Note**: Although an array is accepted, only a single device_id is currently supported. Supplying more than one will return `400 Bad Request`_  *)
    device_ids: string list;
    (* **true**: ensure playback happens on new device.<br>**false** or not provided: keep the current playback state.  *)
    play: bool option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create (device_ids : string list) : t = {
    device_ids = device_ids;
    play = None;
}

